steps:
  - name: gcr.io/cloud-builders/npm
    args: ['install']
  - name: gcr.io/cloud-builders/gcloud
    args: [
      'beta',
      'functions',
      'deploy','${_FUNCTION_NAME}',
      '--project=${_PROJECT_NAME}',
      '--region=${_REGION}',
      '--runtime=nodejs10',
      '--trigger-http',
      '--entry-point=entrypoint',
      '--memory=512MB',
      '--vpc-connector=${_VPC_CONNECTOR}',
      '--set-env-vars',
      'NODE_ENV=${_NODE_ENV},GCLOUD_DATASTORE_PROJECTID=${_GCLOUD_DATASTORE_PROJECTID},GCLOUD_DATASTORE_NAMESPACE=${_GCLOUD_DATASTORE_NAMESPACE},PLATFORM_SETTINGS_SERVER=${_PLATFORM_SETTINGS_SERVER},GCLOUD_SQL_USER=${_GCLOUD_SQL_USER},GCLOUD_SQL_PASSWORD=${_GCLOUD_SQL_PASSWORD},GCLOUD_SQL_DB=${_GCLOUD_SQL_DB},GCLOUD_SQL_INSTANCE=${_GCLOUD_SQL_INSTANCE},ELASTICSEARCH_SERVER=${_ELASTICSEARCH_SERVER},REDIS_HOST=${_REDIS_HOST},REDIS_PORT=${_REDIS_PORT},REDIS_ENABLED=${_REDIS_ENABLED},AUTH_USERNAME=${_AUTH_USERNAME},AUTH_PASSWORD=${_AUTH_PASSWORD}'
    ]
